# Generated by Django 4.1.2 on 2023-01-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_carts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('despatched', 'despatched'), ('in-transit', 'in-transit'), ('canceled', 'canceled')], default='in-cart', max_length=200),
        ),
    ]
